#!/usr/bin/python
'''Start the reactor, and start IRC. The IRC factory will spin up a process that interfaces with F-list.'''
from twisted.internet import reactor
import flistprotocolwsirc
import ircserver
import logging
import os
try:
    from ConfigParser import ConfigParser
except:
    from configparser import ConfigParser

mydir=os.path.dirname(os.path.realpath(__file__))

config = ConfigParser()
config.read(mydir+os.sep+'config.cfg')

logpath = config.get('fchat-irc','logpath')
loglevel = getattr(logging,config.get('fchat-irc','loglevel').upper())

logging.basicConfig(filename=logpath+os.sep+'irc.log',level=loglevel,
         format="%(asctime)s;%(levelname)s;%(message)s",datefmt="%m%d%H%M")
ircfactory = ircserver.IRCServerFactory(reactor)

reactor.listenTCP(8002, ircfactory, interface='127.0.0.1')
reactor.run()


