#!/usr/bin/python
'''Start the reactor, and start IRC. The IRC factory will spin up a process that interfaces with F-list.'''
from twisted.internet import reactor
import flistprotocolwsirc
import ircserver
import logging
import os
mydir=os.path.dirname(os.path.realpath(__file__))
logging.basicConfig(filename=mydir+os.sep+'irc.log',level=logging.DEBUG,
         format="%(asctime)s;%(levelname)s;%(message)s",datefmt="%m%d%H%M")
ircfactory = ircserver.IRCServerFactory(reactor)

reactor.listenTCP(8002, ircfactory, interface='127.0.0.1')
reactor.run()


